/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testDLLCall */

#ifndef _Included_testDLLCall
#define _Included_testDLLCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testDLLCall
 * Method:    cPrintf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testDLLCall_cPrintf
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
